#sb-generated

version: '3.6'
services:
  web:
    environment:
      -  FRONTEND_BUILD=nvm install --latest-npm && npm ci && npm run production
      -  FRONTEND_BUILD_NO_PACKAGE_INSTALL=nvm install --latest-npm && npm run production
      -  FRONTEND_WATCH=nvm install --latest-npm && npm ci && npm run dev-server
      -  FRONTEND_WATCH_NO_PACKAGE_INSTALL=nvm install --latest-npm && npm run dev-server
